### ISSUE TITLE
Previewer Unable to find public constructor for type [view model]

### ISSUE THREAD

**Issue by SimonORorke** [AvaloniaUI/avalonia-docs#466]
### Describe the bug

In the application I'm developing, the previewer fails to show a preview for any of the views in either Visual Studio 2022 or JetBrains Rider.  The error message is "Unable to find public constructor for type [view model]".  In Visual Studio, this is a `System.Xaml.XamlException`.  In Rider, where I have to look in `idea.log` to see the diagnostics, this is a `XamlX.XamlLoadException`. Here's an example from Rider, where a more fulsome trace is provided:
```
XamlX.XamlLoadException: Unable to find public constructor for type FalconProgrammer.ViewModel:FalconProgrammer.ViewModel.MidiForMacrosViewModel() Line 12, position 10.
   at XamlX.Transform.Transformers.ConstructableObjectTransformer.Transform(AstTransformationContext context, IXamlAstNode node)
   at XamlX.Transform.AstTransformationContext.Visitor.Visit(IXamlAstNode node)
   at XamlX.Ast.XamlAstNode.Visit(IXamlAstVisitor visitor)
   at XamlX.Ast.XamlAstNode.VisitList[T](IList`1 list, IXamlAstVisitor visitor)
   at XamlX.Ast.XamlPropertyAssignmentNode.VisitChildren(IXamlAstVisitor visitor)
   at XamlX.Ast.XamlAstNode.Visit(IXamlAstVisitor visitor)
   at XamlX.Ast.XamlAstNode.VisitList[T](IList`1 list, IXamlAstVisitor visitor)
   at XamlX.Ast.XamlAstConstructableObjectNode.VisitChildren(IXamlAstVisitor visitor)
   at XamlX.Ast.XamlAstNode.Visit(IXamlAstVisitor visitor)
   at XamlX.Transform.AstTransformationContext.Visit(IXamlAstNode root, IXamlAstTransformer transformer)
   at XamlX.Compiler.XamlCompiler`2.Transform(XamlDocument doc, Boolean strict)
   at Avalonia.Markup.Xaml.XamlIl.AvaloniaXamlIlRuntimeCompiler.LoadGroupSreCore(IReadOnlyCollection`1 documents, RuntimeXamlLoaderConfiguration configuration)
   at Avalonia.Markup.Xaml.XamlIl.AvaloniaXamlIlRuntimeCompiler.LoadSreCore(RuntimeXamlLoaderDocument document, RuntimeXamlLoaderConfiguration configuration)
   at Avalonia.Markup.Xaml.XamlIl.AvaloniaXamlIlRuntimeCompiler.LoadSre(RuntimeXamlLoaderDocument document, RuntimeXamlLoaderConfiguration configuration)
   at Avalonia.Markup.Xaml.XamlIl.AvaloniaXamlIlRuntimeCompiler.Load(RuntimeXamlLoaderDocument document, RuntimeXamlLoaderConfiguration configuration)
   at Avalonia.Designer.HostApp.DesignXamlLoader.Load(RuntimeXamlLoaderDocument document, RuntimeXamlLoaderConfiguration configuration)
   at Avalonia.DesignerSupport.DesignWindowLoader.LoadDesignerWindow(String xaml, String assemblyPath, String xamlFileProjectPath, Double renderScaling)
   at Avalonia.DesignerSupport.Remote.RemoteDesignerEntryPoint.<>c__DisplayClass18_0.<OnTransportMessage>b__0()
```

### To Reproduce

In Visual Studio or Rider with the required Avalonia extension/plugin installed and making sure preview is enabled, open any view XAML in my open source project https://github.com/SimonORorke/FalconProgrammer.

### Expected behavior

A preview should be shown.

### Avalonia version

11.0

### OS

Windows

### Additional context

All the view models only have constructors with parameters.

**Comment by SimonORorke** [comment]
@timunie 
My pull request commit incorporates some of the points you make, though there were a couple I was not sure about and did not mention.  If applicable, please let me know how I may improve the update.
